# Get all persons
GET http://localhost:3001/api/persons

###

# Get single person by ID
GET http://localhost:3001/api/persons/67e48247e371ae845149b1b4

###

# Delete person by ID
DELETE http://localhost:3001/api/persons/2

###

# Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Jacob Jingleheimer Schmidt",
  "number": "555-555-5555"
}